import Head from "next/head"
import Header from "@/components/Header"
import Main, { Product } from "@/components/Main"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import Footer from "@/components/Footer"
import ShoppingCart from "@/components/ShoppingCart"
import { useEffect, useState } from "react"
import { formattedPrice } from "@/utils/formattedPrice"

export default function index() {
    const queryClient = new QueryClient()

    const [isCartOpen, setIsCartOpen] = useState(false)
    const [cartItems, setCartItems] = useState<Product[]>([])
    const [cartTotal, setCartTotal] = useState(0)

    const toggleCart = () => {
        setIsCartOpen(!isCartOpen)
    }

    useEffect(() => {
        const prices = cartItems.map(item => parseFloat(formattedPrice(item.price)))
        const total = prices.reduce((sum, price) => sum + price, 0)
        setCartTotal(total)
    }, [cartItems])


    return (
        <QueryClientProvider client={queryClient}>
            <Head>
                <title>MKS Sistemas</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header toggleCart={() => setIsCartOpen(true)} cartItems={cartItems} />
            <Main setCartItems={setCartItems} />
            <ShoppingCart isOpen={isCartOpen} toggleCart={toggleCart} cartItems={cartItems} cartTotal={cartTotal} setCartItems={setCartItems} />
            <Footer />
        </QueryClientProvider>
    )
}

